# Declare global configurations
global:
  kibanaEnabled: false
  # elasticsearch:
  #   service:
  #     name: es01

elasticsearch:
  enabled: false
  # fullnameOverride: "elastic"

  security:
    elasticPassword: elasticSearchPas42
    tls:
      restEncryption: false

  coordinating:
    replicaCount: 1

  master:
    replicaCount: 1
    persistence:
      enabled: false

  data:
    replicaCount: 1
    persistence:
      enabled: false

  ingest:
    replicaCount: 1

  ingress:
    enabled: true
    # hostname: es01

## Reference: https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  enabled: true
  fullnameOverride: "kafka"

  persistence:
    enabled: false

  ## https://github.com/bitnami/charts/blob/main/bitnami/zookeeper/values.yaml
  zookeeper:
    persistence:
      enabled: true

    fullnameOverride: "zookeeper"

  ## Kafka provisioning
  provisioning:
    enabled: true
    numPartitions: 1
    replicationFactor: 1

    topics:
    - name: KAFKA_AUDITS_TOPIC
      value: audits
    - name: KAFKA_LOGS_TOPIC
      value: logs
    - name: AccountLookupBcRequests
      value: AccountLookupBcRequests
    - name: AccountLookupBcEvents
      value: AccountLookupBcEvents
    - name: AccountLookupBcResponses
      value: AccountLookupBcResponses
    - name: OperatorBcErrors
      value: OperatorBcErrors
    - name: QuotingBcErrors
      value: QuotingBcErrors
    - name: QuotingBcEvents
      value: QuotingBcEvents
    - name: QuotingBcRequests
      value: QuotingBcRequests
    - name: SettlementsBcRequests
      value: SettlementsBcRequests
    - name: TransfersBcErrors
      value: TransfersBcErrors
    - name: TransfersBcEvents
      value: TransfersBcEvents
    - name: TransfersBcRequests
      value: TransfersBcRequests

    nodeSelector: {}
    tolerations: []
    waitForKafka: true

# https://github.com/bitnami/charts/tree/main/bitnami/mongodb
mongodb:
  enabled: true
  image:
    tag: 5.0.18-debian-11-r8

  fullnameOverride: "mongodb"
  auth:
    enabled: true
  
    rootUser: root
    rootPassword: mongoDbPas42
    usernames:
    - 'mojaloop'
    passwords:
    - 'password'
    databases:
    - 'mlos'

    replicaSetKey: ""
    existingSecret: ""
  persistence:
    enabled: false

# mongo express config 
mongo-express:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx

  mongodbEnableAdmin: true
  mongodbAdminPassword: mongoDbPas42

# https://artifacthub.io/packages/helm/redpanda-data/console?modal=values
# redpanda kakfa console config 
redpanda:
  enabled: true
