version: "3.8"

services:
  fspiop-api-svc:
    image: mojaloop/interop-api-bc-fspiop-api-svc:0.1.1
    volumes:
      - fspiop-api-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - MONGO_URL=${MONGO_URL}
      - PLATFORM_CONFIG_BASE_SVC_URL=${PLATFORM_CONFIG_BASE_SVC_URL}
      - AUTH_Z_SVC_BASEURL=${AUTH_Z_SVC_BASEURL}
      - AUTH_N_SVC_BASEURL=${AUTH_N_SVC_BASEURL}
      - AUTH_N_TOKEN_ISSUER_NAME=${AUTH_N_TOKEN_ISSUER_NAME}
      - AUTH_N_TOKEN_AUDIENCE=${AUTH_N_TOKEN_AUDIENCE}
      - PARTICIPANTS_SVC_URL=${PARTICIPANTS_SVC_URL}
    ports:
      - 4000:4000

  accounts_and_balances_builtin-ledger-grpc-svc:
    image: mojaloop/accounts-and-balances-bc-builtin-ledger-grpc-svc:0.1.6
    volumes:
      - aandb_builtin-ledger-grpc-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - MONGO_URL=${MONGO_URL}
      - PLATFORM_CONFIG_BASE_SVC_URL=${PLATFORM_CONFIG_BASE_SVC_URL}
      - AUTH_Z_SVC_BASEURL=${AUTH_Z_SVC_BASEURL}
      - AUTH_N_SVC_BASEURL=${AUTH_N_SVC_BASEURL}
      - AUTH_N_TOKEN_ISSUER_NAME=${AUTH_N_TOKEN_ISSUER_NAME}
      - AUTH_N_TOKEN_AUDIENCE=${AUTH_N_TOKEN_AUDIENCE}
      - TIGERBEETLE_CLUSTER_ID=${TIGERBEETLE_CLUSTER_ID}
      - TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES=${TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES}
    healthcheck:
      test: nc -z localhost 3350 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3350:3350
    restart: unless-stopped

  accounts_and_balances_coa-grpc-svc:
    image: mojaloop/accounts-and-balances-bc-coa-grpc-svc:0.1.7
    depends_on:
      accounts_and_balances_builtin-ledger-grpc-svc:
        condition: service_healthy
    volumes:
      - aandb_coa-grpc-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - MONGO_URL=${MONGO_URL}
      - PLATFORM_CONFIG_BASE_SVC_URL=${PLATFORM_CONFIG_BASE_SVC_URL}
      - AUTH_Z_SVC_BASEURL=${AUTH_Z_SVC_BASEURL}
      - AUTH_N_SVC_BASEURL=${AUTH_N_SVC_BASEURL}
      - AUTH_N_TOKEN_ISSUER_NAME=${AUTH_N_TOKEN_ISSUER_NAME}
      - AUTH_N_TOKEN_AUDIENCE=${AUTH_N_TOKEN_AUDIENCE}
      - TIGERBEETLE_CLUSTER_ID=${TIGERBEETLE_CLUSTER_ID}
      - TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES=${TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES}
      - BUILTIN_LEDGER_SVC_URL=${BUILTIN_LEDGER_SVC_URL}
    healthcheck:
      test: nc -z localhost 3300 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3300:3300
    restart: unless-stopped

  participants-svc:
    image: mojaloop/participants-bc-participants-svc:0.1.3
    depends_on:
      accounts_and_balances_coa-grpc-svc:
        condition: service_healthy
    volumes:
      - participants-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - MONGO_URL=${MONGO_URL}
      - PLATFORM_CONFIG_BASE_SVC_URL=${PLATFORM_CONFIG_BASE_SVC_URL}
      - AUTH_Z_SVC_BASEURL=${AUTH_Z_SVC_BASEURL}
      - AUTH_N_SVC_BASEURL=${AUTH_N_SVC_BASEURL}
      - AUTH_N_TOKEN_ISSUER_NAME=${AUTH_N_TOKEN_ISSUER_NAME}
      - AUTH_N_TOKEN_AUDIENCE=${AUTH_N_TOKEN_AUDIENCE}
      - TIGERBEETLE_CLUSTER_ID=${TIGERBEETLE_CLUSTER_ID}
      - TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES=${TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES}
      - ACCOUNTS_BALANCES_COA_SVC_URL=${ACCOUNTS_BALANCES_COA_SVC_URL}
    ports:
      - 3010:3010
    restart: unless-stopped

  account-lookup-http-oracle-svc:
    image: mojaloop/account-lookup-bc-http-oracle-svc:0.1.1
    volumes:
      - account-lookup-http-oracle-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
    ports:
      - 3031:3031
    restart: unless-stopped

  account-lookup-svc:
    image: mojaloop/account-lookup-bc-account-lookup-svc:0.1.1
    volumes:
      - account-lookup-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - MONGO_URL=${MONGO_URL}
      - PLATFORM_CONFIG_BASE_SVC_URL=${PLATFORM_CONFIG_BASE_SVC_URL}
      - AUTH_Z_SVC_BASEURL=${AUTH_Z_SVC_BASEURL}
      - AUTH_N_SVC_BASEURL=${AUTH_N_SVC_BASEURL}
      - AUTH_N_TOKEN_ISSUER_NAME=${AUTH_N_TOKEN_ISSUER_NAME}
      - AUTH_N_TOKEN_AUDIENCE=${AUTH_N_TOKEN_AUDIENCE}
      - PARTICIPANTS_SVC_URL=${PARTICIPANTS_SVC_URL}
    ports:
      - 3030:3030
    restart: unless-stopped

  quoting-svc:
    image: mojaloop/quoting-bc-quoting-svc:0.1.0
    volumes:
      - quoting-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - MONGO_URL=${MONGO_URL}
      - PLATFORM_CONFIG_BASE_SVC_URL=${PLATFORM_CONFIG_BASE_SVC_URL}
      - AUTH_Z_SVC_BASEURL=${AUTH_Z_SVC_BASEURL}
      - AUTH_N_SVC_BASEURL=${AUTH_N_SVC_BASEURL}
      - AUTH_N_TOKEN_ISSUER_NAME=${AUTH_N_TOKEN_ISSUER_NAME}
      - AUTH_N_TOKEN_AUDIENCE=${AUTH_N_TOKEN_AUDIENCE}
      - PARTICIPANTS_SVC_URL=${PARTICIPANTS_SVC_URL}
    ports:
      - 3033:3033
    restart: unless-stopped

  ttk_1:
    image: mojaloop/ml-testing-toolkit:v15.0.0
    ports:
      - "4040:4040"
      - "5050:5050"
    command:
      - sh
      - -c
      - "npm start"
  ttk-ui_1:
    image: mojaloop/ml-testing-toolkit-ui:v15.0.0
    ports:
      - "6060:6060"
    volumes:
      - ttk1_ui_data:/usr/share/nginx/html
    environment:
      - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

  ttk_2:
    image: mojaloop/ml-testing-toolkit:v15.0.0
    ports:
      - "4041:4040"
      - "5051:5050"
    command:
      - sh
      - -c
      - "npm start"
  ttk-ui_2:
    image: mojaloop/ml-testing-toolkit-ui:v15.0.0
    ports:
      - "6061:6060"
    volumes:
      - ttk2_ui_data:/usr/share/nginx/html
    environment:
      - API_BASE_URL=http://localhost:5051
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

volumes:
  participants-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/participants-svc
  account-lookup-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/account-lookup-svc
  account-lookup-http-oracle-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/account-lookup-http-oracle-svc
  quoting-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/quoting-svc
  fspiop-api-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/fspiop-api-svc
  aandb_builtin-ledger-grpc-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/aandb_builtin-ledger-grpc-svc
  aandb_coa-grpc-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/aandb_coa-grpc-svc
  ttk1_ui_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/ttk1_ui_data
  ttk2_ui_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/ttk2_ui_data
