apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    mojaloop.service: scheduling-svc
    mojaloop.layer: crosscut
  name: scheduling-svc
spec:
  ports:
    - name: "3150"
      port: 3150
      targetPort: 3150
  selector:
    mojaloop.service: scheduling-svc
status:
  loadBalancer: {}
