# Declare global configurations
global:
  kibanaEnabled: false

############### Kafka and Zookeeper ####################
## Reference: https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  enabled: true
  fullnameOverride: kafka

  persistence:
    enabled: false

  auth:
    clientProtocol: PLAINTEXT
    interBrokerProtocol: PLAINTEXT

  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT

  kraft:
    enabled: false

  broker:
    replicaCount: 1
    persistence:
      enabled: false
    nodeSelector: 
      role: infra

  controller:
    replicaCount: 0
    nodeSelector: 
      role: infra

  extraConfig:
    offsetsTopicReplicationFactor: 1
    defaultReplicationFactor: 1

  ## https://github.com/bitnami/charts/blob/main/bitnami/zookeeper/values.yaml
  zookeeper:
    enabled: true

    persistence:
      enabled: false

    auth:
      client:
        enabled: false

    fullnameOverride: zookeeper

  ## Kafka provisioning
  provisioning:
    enabled: true
    numPartitions: 1
    replicationFactor: 1

    topics:
      -   name: KAFKA_AUDITS_TOPIC
          value: audits
      -   name: KAFKA_LOGS_TOPIC
          value: logs
      -   name: AccountLookupBcRequests
          value: AccountLookupBcRequests
      -   name: AccountLookupBcEvents
          value: AccountLookupBcEvents
      -   name: AccountLookupBcResponses
          value: AccountLookupBcResponses
      -   name: AccountLookupBcErrors
          value: AccountLookupBcErrors
      -   name: OperatorBcErrors
          value: OperatorBcErrors
      -   name: QuotingBcErrors
          value: QuotingBcErrors
      -   name: QuotingBcEvents
          value: QuotingBcEvents
      -   name: QuotingBcRequests
          value: QuotingBcRequests
      -   name: SettlementsBcRequests
          value: SettlementsBcRequests
      -   name: TransfersBcErrors
          value: TransfersBcErrors
      -   name: TransfersBcEvents
          value: TransfersBcEvents
      -   name: TransfersBcRequests
          value: TransfersBcRequests
      -   name: TransfersBcTimeouts
          value: TransfersBcTimeouts
      -   name: SettlementsBcEvents
          value: SettlementsBcEvents
      -   name: SettlementsBcCommands
          value: SettlementsBcCommands
      -   name: PlatformConfigurationBcEvents
          value: PlatformConfigurationBcEvents
      -   name: ParticipantsBcEvents  
          value: ParticipantsBcEvents
          
    nodeSelector: {}
    tolerations: []
    waitForKafka: true

############### RedPanda Console for Kafka  ####################
# https://artifacthub.io/packages/helm/redpanda-data/console?modal=values
# redpanda kakfa console config
redpanda-console:
  enabled: true
  fullnameOverride: rpconsole

  console:
    config:
      kafka:
        brokers:
          -   kafka:9092

  ingress:
    enabled: true
    className: nginx
    hosts:
      -   host: redpanda-console.local
          paths:
            -   path: /
                pathType: ImplementationSpecific

############### MongoDB  ####################
# X64 only => https://github.com/bitnami/charts/tree/main/bitnami/mongodb
# testing for ARM64 : https://artifacthub.io/packages/helm/groundhog2k/mongodb/0.1.0
mongodb:
  enabled: true
  persistence:
    enabled: true
  image:
    tag: 7.0

  fullnameOverride: mongodb
  settings:
    rootUsername: root
    rootPassword: mongoDbPas42
  
  nodeSelector: 
    role: infra


  # initUserDatabase:
  #   dbname: mlos

############### Mongo Express ####################
# mongo express config
mongo-express:
  fullnameOverride: mongo-express
  enabled: true

  image:
    tag: 1.0.0

  ingress:
    enabled: true
    ingressClassName: nginx

  mongodbEnableAdmin: true
  mongodbAdminPassword: mongoDbPas42
  mongodbAdminUsername: root

  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false 
    
############### Redis  ####################
## Reference: https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
redis:
  enabled: true
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  master:
    disableCommands: []
    persistence:
      enabled: true

############### Elasticsearch and Kibana  ####################
elasticsearch:
  enabled: true

  security:
    elasticPassword: elasticSearchPas42
    tls:
      restEncryption: false

  coordinating:
    replicaCount: 1

  master:
    replicaCount: 1
    persistence:
      enabled: true

  data:
    replicaCount: 1
    persistence:
      enabled: true

  ingest:
    replicaCount: 1

  ingress:
    enabled: true

