version: "3.8"

services:
  authentication-svc:
    image: mojaloop/security-bc-authentication-svc:0.0.4
    volumes:
      - authentication-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
    ports:
      - 3201:3201

  authorization-svc:
    image: mojaloop/security-bc-authorization-svc:0.0.4
    volumes:
      - authorization-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
    ports:
      - 3202:3202


volumes:
  authentication-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/authentication-svc
  authorization-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/authorization-svc

