version: "3.8"

services:
  authentication-svc:
    image: mojaloop/security-bc-authentication-svc:0.1.3
    restart: unless-stopped
    volumes:
      - authentication-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - AUTH_N_TOKEN_LIFE_SECS=${AUTH_N_TOKEN_LIFE_SECS}
      - AUTH_N_DEFAULT_AUDIENCE=${AUTH_N_DEFAULT_AUDIENCE}
      - AUTH_N_ISSUER_NAME=${AUTH_N_ISSUER_NAME}
      - PLATFORM_CONFIG_BASE_SVC_URL=${PLATFORM_CONFIG_BASE_SVC_URL}
    ports:
      - 3201:3201
    restart: unless-stopped

  authorization-svc:
    image: mojaloop/security-bc-authorization-svc:0.1.3
    restart: unless-stopped
    volumes:
      - authorization-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - PLATFORM_CONFIG_BASE_SVC_URL=${PLATFORM_CONFIG_BASE_SVC_URL}
    ports:
      - 3202:3202
    restart: unless-stopped

  platform-configuration-svc:
    image: mojaloop/platform-configuration-bc-configuration-svc:latest
    restart: unless-stopped
    volumes:
      - platform-configuration-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
    ports:
      - 3100:3100
    restart: unless-stopped

  auditing-svc:
    image: mojaloop/auditing-bc-auditing-svc:latest
    restart: unless-stopped
    volumes:
      - auditing-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - KAFKA_AUDITS_TOPIC=${KAFKA_AUDITS_TOPIC}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_AUDITS_INDEX=${ELASTICSEARCH_AUDITS_INDEX}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    restart: unless-stopped

  logging-svc:
    image: mojaloop/logging-bc-logging-svc:latest
    restart: unless-stopped
    volumes:
      - logging-svc_data:/app/data
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_LOGS_TOPIC=${KAFKA_LOGS_TOPIC}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_AUDITS_INDEX=${ELASTICSEARCH_AUDITS_INDEX}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    restart: unless-stopped

volumes:
  authentication-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/authentication-svc
  authorization-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/authorization-svc
  platform-configuration-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/platform-configuration-svc
  auditing-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/auditing-svc
  logging-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_VOLUME_DEVICE_PATH}/data/logging-svc
