apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    mojaloop.service: reporting-api-svc
    mojaloop.layer: reporting 
  name: reporting-api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: reporting-api-svc
  strategy: {}
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        mojaloop.service: reporting-api-svc
        mojaloop.layer: reporting 
    spec:
      containers:
        - env:
            - name: AUTH_N_SVC_BASEURL
            - name: AUTH_N_TOKEN_AUDIENCE
            - name: AUTH_N_TOKEN_ISSUER_NAME
            - name: AUTH_Z_SVC_BASEURL
            - name: KAFKA_AUDITS_TOPIC
            - name: KAFKA_LOGS_TOPIC
            - name: KAFKA_URL
            - name: MONGO_URL
            - name: PLATFORM_CONFIG_BASE_SVC_URL
          image: mojaloop/reporting-bc-reporting-api-svc:0.3.6
          livenessProbe:
            exec:
              command:
                - nc -z localhost 5005 || exit -1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: reporting-api-svc
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
